# site
site_name: 'Aron Strandberg'

# options
markdown: rdiscount
rdiscount:
  extensions: [smart]
highlighter: pygments

exclude: [projects/dbuggen]

# sass
sass:
  sass_dir: _scss
  style: :expanded

# dev options
port: 1337
