// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    return $.ajax({
      type: "GET",
      url: "https://api.instagram.com/v1/users/30699936/media/recent/?access_token=30699936.9d8a07f.7a573e8a48bf47478f8d1f9fc5b01ce9&callback=callback",
      jsonp: "callback",
      dataType: "jsonp",
      success: function(response) {
        var html, img, url, _i, _len, _ref;
        console.log("hej");
        html = "";
        url = "";
        _ref = response["data"];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          img = _ref[_i];
          url = img["images"]["standard_resolution"]["url"];
          html += "<img src='" + url + "'>";
          html += "<p>" + img["caption"]["text"] + "</p>";
        }
        $('#photos').html(html);
        return false;
      }
    });
  });

}).call(this);
