// Generated by CoffeeScript 1.9.2
$(function() {
  var chart, data, datatype, height, n, redraw, refresh, w, width, x, y;
  width = document.documentElement.clientWidth * 0.3;
  height = document.documentElement.clientHeight * 0.8;
  n = 4;
  datatype = "velocity";
  data = window.data[datatype];
  x = d3.scale.linear().domain([0, data.length]).range([0, width]);
  y = d3.scale.linear().domain([0, n]).rangeRound([0, height]);
  w = function() {
    return width / data.length;
  };
  chart = d3.select("#chart").append("svg:svg").attr("width", width).attr("height", height);
  chart.selectAll("rect").data(data).enter().append("svg:rect").attr("x", function(d, i) {
    return x(i);
  }).attr("y", function(d) {
    return height - y(d);
  }).attr('width', w()).attr("height", function(d) {
    return y(d);
  });
  redraw = function() {
    var rect;
    rect = chart.selectAll('rect').data(data);
    rect.enter().insert('svg:rect', 'line').attr('x', function(d, i) {
      return x(i);
    }).attr('y', function(d) {
      return height - y(d);
    }).attr('width', w()).attr('height', function(d) {
      return y(d);
    }).transition().duration(window.interval).attr('x', function(d, i) {
      return x(i);
    });
    rect.transition().duration(window.interval).attr('x', function(d, i) {
      return x(i);
    }).attr('y', function(d) {
      return height - y(d);
    }).attr('width', w()).attr('height', function(d) {
      return y(d);
    });
  };
  refresh = function() {
    data = window.data[datatype];
    x.domain([0, data.length]);
    y.domain([0, Math.max.apply(null, data)]);
    return redraw();
  };
  return setInterval(refresh, window.interval);
});


//# sourceMappingURL=graph.js.map
