// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var ajax, next;
    next = "https://api.instagram.com/v1/users/30699936/media/recent/?access_token=30699936.9d8a07f.7a573e8a48bf47478f8d1f9fc5b01ce9&callback=callback&count=32";
    ajax = function(url) {
      return $.ajax({
        type: "GET",
        url: url,
        jsonp: "callback",
        dataType: "jsonp",
        success: function(response) {
          var html, img, _i, _len, _ref;
          html = "";
          url = "";
          _ref = response["data"];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            img = _ref[_i];
            url = img["images"]["standard_resolution"]["url"];
            html += "<img src='" + url + "'>";
            html += "<p class='caption'>" + img["caption"]["text"] + "</p>";
            html += "<p class='likes'>" + img["likes"]["count"] + "</p>";
          }
          $('#photos').append(html);
          next = response["pagination"]["next_url"];
          console.log(response["pagination"]["next_max_id"]);
          return console.log(next);
        },
        complete: function() {
          return ajax(next);
        }
      });
    };
    return ajax(next);
  });

}).call(this);
