// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return $('.scroll-top').click(function() {
      $('html,body').animate({
        scrollTop: 0
      }, 400);
      return false;
    });
  });

}).call(this);
