// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    return $('.scroll-to-top').click(function() {
      console.log("clicky");
      $('html,body').animate({
        scrollTop: 0
      }, 400);
      return false;
    });
  });

}).call(this);
